# render.yaml (Final Version with Shared Disk)
# This blueprint defines all services and the shared disk for uploads.

# --- NEW: Define the shared disk once at the top level ---
disks:
  - name: slidea-uploads
    sizeGB: 1 # Start with 1 GB, you can increase this later
    mountPath: /app/app/static/uploads

# Managed Database Definition
databases:
  - name: slidea-db
    plan: standard

# Managed Redis Definition
redis:
  - name: slidea-redis
    plan: standard

# Application Services Definition
services:
  # Flask Web Service (using Gunicorn)
  - type: web
    name: slidea-web
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    # --- Attach the shared disk defined above ---
    disks:
      - name: slidea-uploads
        mountPath: /app/app/static/uploads
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 70
      targetCPUPercent: 70
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker Service
  - type: worker
    name: slidea-worker
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    # --- Attach the SAME shared disk defined above ---
    disks:
      - name: slidea-uploads
        mountPath: /app/app/static/uploads
    scaling:
      minInstances: 1
      maxInstances: 5
      targetMemoryPercent: 70
      targetCPUPercent: 70
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          envVarKey: SECRET_KEY
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false
