# render.yaml
# Blueprint for deploying the SlideaAI Flask application on Render
# Using top-level keys for DB/Redis AND explicit linking within services.

# Managed Database Definition
databases:
  - name: slidea-db
    plan: starter # IMPORTANT: Use a paid plan for persistence.

# Managed Redis Definition
redis:
  - name: slidea-redis
    plan: free # Free tier is usually okay for Redis cache/broker initially

# Application Services Definition
services:
  # Flask Web Service (using Gunicorn)
  - type: web
    name: slidea-web
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    # Explicitly link the database and redis instances defined above
    databases:
      - name: slidea-db # Name must match the database defined above
        # property: connectionString # Not needed, Render injects DATABASE_URL by default
    redis:
      - name: slidea-redis # Name must match the redis defined above
        # property: connectionString # Not needed, Render injects REDIS_URL by default
    envVars:
      # --- Core Flask/Python Settings ---
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # --- Database & Redis Connection ---
      # DATABASE_URL and REDIS_URL are automatically injected by Render
      # due to the databases: and redis: links above.
      # Ensure your config.py reads os.environ.get('DATABASE_URL') and os.environ.get('REDIS_URL')
      # --- Celery Config (Reads REDIS_URL from environment in config.py) ---
      # NO EXPLICIT CELERY URLs NEEDED HERE if config.py uses REDIS_URL
      # --- External API Keys (Set these in Render Dashboard Environment Secrets) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker Service
  - type: worker
    name: slidea-worker
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    # Explicitly link the database and redis instances defined above
    databases:
      - name: slidea-db # Name must match the database defined above
        # property: connectionString # Not needed
    redis:
      - name: slidea-redis # Name must match the redis defined above
        # property: connectionString # Not needed
    envVars:
      # Inherit most variables from the web service or set explicitly
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService: # Get the same generated key as the web service
          # type: web # Type is not needed here per feedback
          name: slidea-web
          envVarKey: SECRET_KEY
      # --- Database & Redis Connection (Render injects these automatically) ---
      # DATABASE_URL and REDIS_URL are automatically injected
      # --- Celery Config (Reads REDIS_URL from environment in config.py) ---
      # NO EXPLICIT CELERY URLs NEEDED HERE if config.py uses REDIS_URL
      # --- External API Keys (Set these in Render Dashboard Environment Secrets) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
