# render.yaml
# Blueprint for deploying the SlideaAI Flask application on Render
# Using top-level keys for DB/Redis, explicit Celery Env Vars in services

# Managed Database Definition
databases:
  - name: slidea-db
    plan: starter # IMPORTANT: Use a paid plan for persistence.

# Managed Redis Definition
redis:
  - name: slidea-redis
    plan: free # Free tier is usually okay for Redis cache/broker initially

# Application Services Definition
services:
  # Flask Web Service (using Gunicorn)
  - type: web
    name: slidea-web
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # --- Database & Redis Connection ---
      # DATABASE_URL and REDIS_URL are automatically injected by Render
      # --- Explicit Celery Config using Render's REDIS_URL ---
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL # Explicitly set CELERY_BROKER_URL from injected REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL # Explicitly set CELERY_RESULT_BACKEND from injected REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker Service
  - type: worker
    name: slidea-worker
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app # Worker still needs app context
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          envVarKey: SECRET_KEY
      # --- Database & Redis Connection ---
      # DATABASE_URL and REDIS_URL are automatically injected
      # --- Explicit Celery Config using Render's REDIS_URL ---
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL # Explicitly set CELERY_BROKER_URL from injected REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL # Explicitly set CELERY_RESULT_BACKEND from injected REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      # --- ADDED MISSING STRIPE PRICE IDs FOR WORKER ---
      # These are needed so config.py can build PLAN_NAME_MAP in the worker
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
