# render.yaml (Upgraded for Production)
# Blueprint for deploying the SlideaAI Flask application on Render

# Managed Database Definition
databases:
  - name: slidea-db
    plan: standard # UPGRADED: From starter to standard for persistence and performance.

# Managed Redis Definition
redis:
  - name: slidea-redis
    plan: standard # UPGRADED: From free to a paid plan for more memory.

# Application Services Definition
services:
  # Flask Web Service (using Gunicorn)
  - type: web
    name: slidea-web
    env: docker
    plan: standard # UPGRADED: From starter to handle more user traffic.
    dockerfilePath: ./Dockerfile
    # Add auto-scaling rules here for production
    scaling:
      minInstances: 1
      maxInstances: 3 # Example: scale up to 3 instances under load
      targetMemoryPercent: 70 # Example: scale up if memory usage is > 70%
      targetCPUPercent: 70 # Example: scale up if CPU usage is > 70%
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4" # Set based on your plan's CPU count (e.g., Standard has 2 vCPU, so (2*2)+1=5 is a good start)
      # --- Database & Redis Connection ---
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker Service
  - type: worker
    name: slidea-worker
    env: docker
    plan: standard # UPGRADED: From starter to process AI tasks faster.
    dockerfilePath: ./Dockerfile
    # Add auto-scaling rules here for production
    scaling:
      minInstances: 1
      maxInstances: 5 # Example: scale up to 5 workers if queue is long
      targetMemoryPercent: 70
      targetCPUPercent: 70
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          envVarKey: SECRET_KEY
      # --- Database & Redis Connection ---
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
