# render.yaml
# Blueprint for deploying the SlideaAI Flask application on Render
# NOTE: Redis is REMOVED from this file and must be added manually in Render Dashboard.

# Managed Database Definition
databases:
  - name: slidea-db
    plan: starter # IMPORTANT: Use a paid plan for persistence.

# Application Services Definition
services:
  # Flask Web Service (using Gunicorn)
  - type: web
    name: slidea-web
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # DATABASE_URL is automatically injected by Render
      # REDIS_URL MUST BE ADDED MANUALLY in Render Environment Variables
      # --- Celery Config (Reads REDIS_URL from environment in config.py) ---
      # Ensure config.py reads os.environ.get('REDIS_URL') for Celery config
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker Service
  - type: worker
    name: slidea-worker
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          type: web
          name: slidea-web
          envVarKey: SECRET_KEY
      # DATABASE_URL is automatically injected
      # REDIS_URL MUST BE ADDED MANUALLY in Render Environment Variables
      # --- Celery Config (Reads REDIS_URL from environment in config.py) ---
      # Ensure config.py reads os.environ.get('REDIS_URL') for Celery config
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
