# Slidea — Web + Worker + KeyValue (Redis) + MinIO (S3)
# Uses EXISTING Postgres DB named "slidea-db" (create in dashboard)

services:
  # Redis (Celery broker/result) — keep plan to match your existing instance
  - type: keyvalue
    name: slidea-redis
    plan: standard
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (dev)

  # MinIO object storage (private S3 API)
  - type: pserv
    name: slidea-minio
    runtime: docker
    plan: starter
    repo: https://github.com/render-examples/minio.git
    numInstances: 1
    envVars:
      - key: MINIO_ROOT_USER
        value: slideaadmin
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "10000"
    disk:
      name: uploads
      mountPath: /data
      sizeGB: 1

  # Flask Web
  - type: web
    name: slidea-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "2"
      - key: SECRET_KEY
        generateValue: true

      # Postgres (must exist in dashboard as "slidea-db")
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis
      - key: REDIS_URL
        fromService:
          name: slidea-redis
          type: keyvalue
          property: connectionString

      # S3/MinIO for storage.py
      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      # Third-party secrets
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      # Let entrypoint choose command
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker (same image; command chosen by entrypoint via SERVICE_TYPE)
  - type: worker
    name: slidea-worker
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production

      - key: SECRET_KEY
        fromService:
          name: slidea-web
          type: web
          envVarKey: SECRET_KEY

      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      - key: REDIS_URL
        fromService:
          name: slidea-redis
          type: keyvalue
          property: connectionString

      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
