# Slidea — Render blueprint (Hobby-friendly, Web + Worker + Postgres + KeyValue + MinIO)

databases:
  - name: slidea-db
    plan: starter
    # Lock this down later in prod
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (dev)

services:
  # Redis-compatible store (for Celery broker/result)
  - type: keyvalue
    name: slidea-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (dev)

  # MinIO object storage (S3 API) for shared uploads
  - type: pserv
    name: slidea-minio
    runtime: docker
    plan: starter
    repo: https://github.com/render-examples/minio.git
    numInstances: 1
    envVars:
      - key: MINIO_ROOT_USER
        sync: false            # set in dashboard
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "10000"
    disk:                      # one service only; this is fine
      name: uploads
      mountPath: /data
      sizeGB: 1

  # Flask Web (Gunicorn via your Dockerfile)
  - type: web
    name: slidea-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    healthCheckPath: /health    # make sure your app serves this 200 OK
    envVars:
      # Python/Flask
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "2"
      - key: SECRET_KEY
        generateValue: true

      # Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis (full URL for Celery)
      - key: REDIS_URL
        fromService:
          name: slidea-redis
          type: keyvalue
          property: connectionString

      # S3/MinIO (used by storage.py)
      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      # Third-party secrets (set in dashboard)
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      # Optional app flags
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker (same image as web)
  - type: worker
    name: slidea-worker
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production

      # Keep SECRET_KEY in sync with web
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          type: web
          envVarKey: SECRET_KEY

      # Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis (same URL as web)
      - key: REDIS_URL
        fromService:
          name: slidea-redis
          type: keyvalue
          property: connectionString

      # S3/MinIO (same as web)
      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      # Third-party secrets
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
