# render.yaml
# Blueprint for deploying the SlideaAI Flask application on Render
# Defining DB at top-level, Redis as keyvalue service, injecting URLs

# Managed Database Definition
databases:
  - name: slidea-db
    plan: starter # IMPORTANT: Use a paid plan for persistence.
    # databaseName: slidea_db # Optional
    # user: slidea_user # Optional

# Application Services Definition
services:
  # Flask Web Service (using Gunicorn)
  - type: web
    name: slidea-web
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    envVars:
      # --- Core Flask/Python Settings ---
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      # --- Database Connection ---
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString # Standard property for databases
      # --- Redis Connection ---
      - key: REDIS_URL
        fromService:
          type: keyvalue # Reference the type of the Redis service
          name: slidea-redis
          property: connectionString # Standard property for redis/keyvalue
      # --- Celery Config (Reads REDIS_URL from environment) ---
      # NO EXPLICIT CELERY URLs NEEDED HERE if config.py uses REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker Service
  - type: worker
    name: slidea-worker
    env: docker
    plan: starter # IMPORTANT: Use a paid plan
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService: # Get the same generated key as the web service
          type: web # Correct type for referencing web service env var
          name: slidea-web
          envVarKey: SECRET_KEY
      # --- Database Connection ---
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString
      # --- Redis Connection ---
      - key: REDIS_URL
        fromService:
          type: keyvalue # Reference the type of the Redis service
          name: slidea-redis
          property: connectionString
      # --- Celery Config (Reads REDIS_URL from environment) ---
      # NO EXPLICIT CELERY URLs NEEDED HERE if config.py uses REDIS_URL
      # --- Secrets (Set in Render UI) ---
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      # --- Service Type ---
      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"

  # Redis Service (Defined as Key-Value Store)
  - type: keyvalue # Define Redis using the 'keyvalue' type
    name: slidea-redis
    plan: free # Free tier is usually okay for Redis cache/broker initially
    ipAllowList: [] # Optional: Allow connections from anywhere (adjust if needed)
    # Version is managed by Render for keyvalue type
