# render.yaml — Slidea (Web + Worker + Postgres + KeyValue + MinIO) — Hobby friendly

databases:
  - name: slidea-db
    plan: starter            # was 'standard' → use starter on Hobby

services:
  # Redis-compatible Key Value
  - type: keyvalue
    name: slidea-redis
    plan: starter            # was 'standard'
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (dev)

  # MinIO object storage (S3 API) for shared uploads
  - type: pserv
    name: slidea-minio
    runtime: docker
    plan: starter            # was 'standard'
    repo: https://github.com/render-examples/minio.git
    numInstances: 1
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "10000"
    disk:                    # singular; only this service gets a disk
      name: uploads
      mountPath: /data
      sizeGB: 1

  # Flask Web
  - type: web
    name: slidea-web
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1          # no autoscaling on Hobby
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "2"           # small dyno, keep modest
      - key: SECRET_KEY
        generateValue: true

      # Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis (assemble URL in code)
      - key: REDIS_HOST
        fromService:
          name: slidea-redis
          type: keyvalue
          property: host
      - key: REDIS_PORT
        fromService:
          name: slidea-redis
          type: keyvalue
          property: port

      # S3/MinIO
      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      # Third-party secrets
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker
  - type: worker
    name: slidea-worker
    runtime: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          type: web
          envVarKey: SECRET_KEY

      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      - key: REDIS_HOST
        fromService:
          name: slidea-redis
          type: keyvalue
          property: host
      - key: REDIS_PORT
        fromService:
          n
