# render.yaml — Slidea (Web + Worker + Managed Postgres + Managed Redis + Shared Disk)

# --- Shared Disk ---
disks:
  - name: slidea-uploads
    sizeGB: 1
    mountPath: /app/app/static/uploads

# --- Managed Postgres ---
databases:
  - name: slidea-db
    plan: standard

# --- Services ---
services:
  # Managed Redis
  - type: redis
    name: slidea-redis
    plan: standard

  # Flask Web (Gunicorn via Dockerfile)
  - type: web
    name: slidea-web
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    disks:
      - name: slidea-uploads
        mountPath: /app/app/static/uploads
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 70
    envVars:
      # Lang/Flask
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "4"

      # App secrets
      - key: SECRET_KEY
        generateValue: true

      # DB URL from managed Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis URL from managed Redis
      - key: REDIS_URL
        fromService:
          name: slidea-redis
          property: connectionString

      # Celery points to Redis
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL

      # Stripe / OpenAI (set in Render UI)
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      # Service tags (optional, for your app logic)
      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker (same image)
  - type: worker
    name: slidea-worker
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    disks:
      - name: slidea-uploads
        mountPath: /app/app/static/uploads
    scaling:
      minInstances: 1
      maxInstances: 5
      targetCPUPercent: 70
      targetMemoryPercent: 70
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production

      # Reuse the web's SECRET_KEY
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          envVarKey: SECRET_KEY

      # DB URL from managed Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis URL from managed Redis
      - key: REDIS_URL
        fromService:
          name: slidea-redis
          property: connectionString

      # Celery to Redis
      - key: CELERY_BROKER_URL
        fromEnvVar: REDIS_URL
      - key: CELERY_RESULT_BACKEND
        fromEnvVar: REDIS_URL

      # Secrets (set in UI)
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
