# render.yaml — Slidea (Web + Worker + Postgres + KeyValue + MinIO)

databases:
  - name: slidea-db
    plan: standard
    # Optional: open while you iterate; tighten later
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (dev)

services:
  # Redis-compatible Key Value
  - type: keyvalue
    name: slidea-redis
    plan: standard
    # REQUIRED by spec
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (dev)

  # MinIO object storage for shared uploads
  - type: pserv
    name: slidea-minio
    runtime: docker
    plan: standard
    repo: https://github.com/render-examples/minio.git
    envVars:
      - key: MINIO_ROOT_USER
        sync: false
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
      - key: PORT
        value: "10000"
    disk:
      name: uploads
      mountPath: /data
      sizeGB: 1

  # Flask Web
  - type: web
    name: slidea-web
    runtime: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 70
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: WEB_CONCURRENCY
        value: "4"
      - key: SECRET_KEY
        generateValue: true

      # Postgres
      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      # Redis pieces (assemble URL in code)
      - key: REDIS_HOST
        fromService:
          name: slidea-redis
          type: keyvalue
          property: host
      - key: REDIS_PORT
        fromService:
          name: slidea-redis
          type: keyvalue
          property: port

      # S3/MinIO
      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      # Third-party secrets (set in UI)
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_ENDPOINT_SECRET
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      - key: SERVICE_TYPE
        value: web
      - key: IS_WEB_SERVICE
        value: "true"

  # Celery Worker
  - type: worker
    name: slidea-worker
    runtime: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 5
      targetCPUPercent: 70
      targetMemoryPercent: 70
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        fromService:
          name: slidea-web
          type: web
          envVarKey: SECRET_KEY

      - key: DATABASE_URL
        fromDatabase:
          name: slidea-db
          property: connectionString

      - key: REDIS_HOST
        fromService:
          name: slidea-redis
          type: keyvalue
          property: host
      - key: REDIS_PORT
        fromService:
          name: slidea-redis
          type: keyvalue
          property: port

      - key: S3_ENDPOINT
        value: http://slidea-minio:10000
      - key: S3_ACCESS_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_USER
      - key: S3_SECRET_KEY
        fromService:
          name: slidea-minio
          type: pserv
          envVarKey: MINIO_ROOT_PASSWORD
      - key: S3_BUCKET
        value: slidea-uploads
      - key: S3_USE_SSL
        value: "false"

      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID_PRO
        sync: false
      - key: STRIPE_PRICE_ID_CREATOR
        sync: false

      - key: SERVICE_TYPE
        value: worker
      - key: IS_WEB_SERVICE
        value: "false"
