"""Add celery_chord_id to Presentation model

Revision ID: 28e856ceabb5
Revises: e84396b48ef1
Create Date: 2025-04-05 16:27:30.077345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e856ceabb5'
down_revision = 'e84396b48ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_chord_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_presentations_celery_chord_id'), ['celery_chord_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presentations_celery_chord_id'))
        batch_op.drop_column('celery_chord_id')

    # ### end Alembic commands ###
