"""Add stripe and credit fields to User model

Revision ID: de8b9dc01657
Revises: 28e856ceabb5 # <-- Make sure this matches your previous revision ID
Create Date: 2025-04-25 15:XX:XX.XXXXXX # <-- Your actual date

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8b9dc01657'
down_revision = '28e856ceabb5' # <-- Make sure this matches your previous revision ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility, but works for others too
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_price_id', sa.String(length=255), nullable=True))
        # *** Ensure server_default is present ***
        batch_op.add_column(sa.Column('subscription_plan_name', sa.String(length=50), server_default='free', nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True))
        # *** Ensure server_default is present ***
        batch_op.add_column(sa.Column('credits_remaining', sa.Integer(), server_default='0', nullable=False)) # THIS LINE IS CRITICAL
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    # Add columns to presentations table (if they were added in the model)
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('font_choice', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('creativity_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_column('creativity_score')
        batch_op.drop_column('font_choice')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_column('credits_remaining')
        batch_op.drop_column('subscription_current_period_end')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('subscription_plan_name')
        batch_op.drop_column('stripe_price_id')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
