"""Initial migration for PostgreSQL

Revision ID: e84396b48ef1
Revises: 
Create Date: 2025-04-05 15:22:02.022424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84396b48ef1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('presentations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('style_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_edited_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending_text', 'pending_visuals', 'visuals_complete', 'generation_failed', name='presentationstatus', native_enum=False, create_constraint=True), server_default='pending_text', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presentations_user_id'), ['user_id'], unique=False)

    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presentation_id', sa.Integer(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_gen_prompt', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_style_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['presentation_id'], ['presentations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slides_presentation_id'), ['presentation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slides_presentation_id'))

    op.drop_table('slides')
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presentations_user_id'))

    op.drop_table('presentations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
